

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class supplierStorageItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität supplierStorageItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public supplierStorageItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public supplierStorageItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.supplierStorageItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.supplierStorageItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void supplierStorageItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void supplierStorageItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PK_supplierStorage
        {
            get
            {
                return global::LightSwitchApplication.supplierStorageItem.DetailsClass.GetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.PK_supplierStorage);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_supplierStorage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_supplierStorage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_supplierStorage_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int amount
        {
            get
            {
                return global::LightSwitchApplication.supplierStorageItem.DetailsClass.GetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.amount);
            }
            set
            {
                global::LightSwitchApplication.supplierStorageItem.DetailsClass.SetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.amount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.beerSuppliersItem beerSuppliersItem1
        {
            get
            {
                return global::LightSwitchApplication.supplierStorageItem.DetailsClass.GetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1);
            }
            set
            {
                global::LightSwitchApplication.supplierStorageItem.DetailsClass.SetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerSuppliersItem1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerSuppliersItem1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerSuppliersItem1_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.suppliersItem suppliersItem1
        {
            get
            {
                return global::LightSwitchApplication.supplierStorageItem.DetailsClass.GetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1);
            }
            set
            {
                global::LightSwitchApplication.supplierStorageItem.DetailsClass.SetValue(this, global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void suppliersItem1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void suppliersItem1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void suppliersItem1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.supplierStorageItem,
                global::LightSwitchApplication.supplierStorageItem.DetailsClass,
                global::LightSwitchApplication.supplierStorageItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.PK_supplierStorage;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>.Entry
                __supplierStorageItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.supplierStorageItem.DetailsClass.__supplierStorageItem_CreateNew,
                    global::LightSwitchApplication.supplierStorageItem.DetailsClass.__supplierStorageItem_Created,
                    global::LightSwitchApplication.supplierStorageItem.DetailsClass.__supplierStorageItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.supplierStorageItem __supplierStorageItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.supplierStorageItem> es)
            {
                return new global::LightSwitchApplication.supplierStorageItem(es);
            }
            private static void __supplierStorageItem_Created(global::LightSwitchApplication.supplierStorageItem e)
            {
                e.supplierStorageItem_Created();
            }
            private static bool __supplierStorageItem_AllowSaveWithErrors(global::LightSwitchApplication.supplierStorageItem e)
            {
                bool result = false;
                e.supplierStorageItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int> PK_supplierStorage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.PK_supplierStorage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int> amount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.amount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem> beerSuppliersItem1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem> suppliersItem1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PK_supplierStorage { get; }
                new int amount { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation beerSuppliersItem1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation suppliersItem1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Entry
                    PK_supplierStorage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Entry(
                        "PK_supplierStorage",
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._PK_supplierStorage_Stub,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._PK_supplierStorage_ComputeIsReadOnly,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._PK_supplierStorage_Validate,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._PK_supplierStorage_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._PK_supplierStorage_OnValueChanged);
                private static void _PK_supplierStorage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.supplierStorageItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PK_supplierStorage, sf);
                }
                private static bool _PK_supplierStorage_ComputeIsReadOnly(global::LightSwitchApplication.supplierStorageItem e)
                {
                    bool result = false;
                    e.PK_supplierStorage_IsReadOnly(ref result);
                    return result;
                }
                private static void _PK_supplierStorage_Validate(global::LightSwitchApplication.supplierStorageItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PK_supplierStorage_Validate(r);
                }
                private static int _PK_supplierStorage_GetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PK_supplierStorage;
                }
                private static void _PK_supplierStorage_OnValueChanged(global::LightSwitchApplication.supplierStorageItem e)
                {
                    e.PK_supplierStorage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Entry
                    amount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Entry(
                        "amount",
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_Stub,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_ComputeIsReadOnly,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_Validate,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_GetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_SetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._amount_OnValueChanged);
                private static void _amount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.supplierStorageItem.DetailsClass d, object sf)
                {
                    c(d, ref d._amount, sf);
                }
                private static bool _amount_ComputeIsReadOnly(global::LightSwitchApplication.supplierStorageItem e)
                {
                    bool result = false;
                    e.amount_IsReadOnly(ref result);
                    return result;
                }
                private static void _amount_Validate(global::LightSwitchApplication.supplierStorageItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.amount_Validate(r);
                }
                private static int _amount_GetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.ImplementationEntity.amount;
                }
                private static void _amount_SetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.amount = v;
                }
                private static void _amount_OnValueChanged(global::LightSwitchApplication.supplierStorageItem e)
                {
                    e.amount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem>.Entry
                    beerSuppliersItem1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem>.Entry(
                        "beerSuppliersItem1",
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_Stub,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_ComputeIsReadOnly,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_Validate,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_GetCoreImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_GetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_SetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_Refresh,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._beerSuppliersItem1_OnValueChanged);
                private static void _beerSuppliersItem1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem>.Data> c, global::LightSwitchApplication.supplierStorageItem.DetailsClass d, object sf)
                {
                    c(d, ref d._beerSuppliersItem1, sf);
                }
                private static bool _beerSuppliersItem1_ComputeIsReadOnly(global::LightSwitchApplication.supplierStorageItem e)
                {
                    bool result = false;
                    e.beerSuppliersItem1_IsReadOnly(ref result);
                    return result;
                }
                private static void _beerSuppliersItem1_Validate(global::LightSwitchApplication.supplierStorageItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.beerSuppliersItem1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _beerSuppliersItem1_GetCoreImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.ImplementationEntity.beerSuppliersItem1;
                }
                private static global::LightSwitchApplication.beerSuppliersItem _beerSuppliersItem1_GetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.beerSuppliersItem, global::LightSwitchApplication.beerSuppliersItem.DetailsClass>(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1, ref d._beerSuppliersItem1);
                }
                private static void _beerSuppliersItem1_SetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d, global::LightSwitchApplication.beerSuppliersItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1, ref d._beerSuppliersItem1, (i, ev) => i.beerSuppliersItem1 = ev, v);
                }
                private static void _beerSuppliersItem1_Refresh(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.beerSuppliersItem1, ref d._beerSuppliersItem1);
                }
                private static void _beerSuppliersItem1_OnValueChanged(global::LightSwitchApplication.supplierStorageItem e)
                {
                    e.beerSuppliersItem1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem>.Entry
                    suppliersItem1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem>.Entry(
                        "suppliersItem1",
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_Stub,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_ComputeIsReadOnly,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_Validate,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_GetCoreImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_GetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_SetImplementationValue,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_Refresh,
                        global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties._suppliersItem1_OnValueChanged);
                private static void _suppliersItem1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem>.Data> c, global::LightSwitchApplication.supplierStorageItem.DetailsClass d, object sf)
                {
                    c(d, ref d._suppliersItem1, sf);
                }
                private static bool _suppliersItem1_ComputeIsReadOnly(global::LightSwitchApplication.supplierStorageItem e)
                {
                    bool result = false;
                    e.suppliersItem1_IsReadOnly(ref result);
                    return result;
                }
                private static void _suppliersItem1_Validate(global::LightSwitchApplication.supplierStorageItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.suppliersItem1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _suppliersItem1_GetCoreImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.ImplementationEntity.suppliersItem1;
                }
                private static global::LightSwitchApplication.suppliersItem _suppliersItem1_GetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.suppliersItem, global::LightSwitchApplication.suppliersItem.DetailsClass>(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1, ref d._suppliersItem1);
                }
                private static void _suppliersItem1_SetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass d, global::LightSwitchApplication.suppliersItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1, ref d._suppliersItem1, (i, ev) => i.suppliersItem1 = ev, v);
                }
                private static void _suppliersItem1_Refresh(global::LightSwitchApplication.supplierStorageItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.supplierStorageItem.DetailsClass.PropertySetProperties.suppliersItem1, ref d._suppliersItem1);
                }
                private static void _suppliersItem1_OnValueChanged(global::LightSwitchApplication.supplierStorageItem e)
                {
                    e.suppliersItem1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Data _PK_supplierStorage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, int>.Data _amount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.beerSuppliersItem>.Data _beerSuppliersItem1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.supplierStorageItem, global::LightSwitchApplication.supplierStorageItem.DetailsClass, global::LightSwitchApplication.suppliersItem>.Data _suppliersItem1;
            
        }
    
        #endregion
    }
    
    #endregion
}
