

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class beerRecipientsItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität beerRecipientsItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public beerRecipientsItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public beerRecipientsItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.beerRecipientsItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.beerRecipientsItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerRecipientsItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerRecipientsItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string name
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.name);
            }
            set
            {
                global::LightSwitchApplication.beerRecipientsItem.DetailsClass.SetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.countriesItem countriesItem
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem);
            }
            set
            {
                global::LightSwitchApplication.beerRecipientsItem.DetailsClass.SetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void countriesItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void countriesItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void countriesItem_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.contactDetailsItem> contactDetails
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.contactDetails);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.contactDetailsItem> contactDetailsQuery
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.contactDetails);
            }
        }

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.deliveriesItem> deliveries
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetValue(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.deliveries);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.deliveriesItem> deliveriesQuery
        {
            get
            {
                return global::LightSwitchApplication.beerRecipientsItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.deliveries);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.beerRecipientsItem,
                global::LightSwitchApplication.beerRecipientsItem.DetailsClass,
                global::LightSwitchApplication.beerRecipientsItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>.Entry
                __beerRecipientsItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.beerRecipientsItem.DetailsClass.__beerRecipientsItem_CreateNew,
                    global::LightSwitchApplication.beerRecipientsItem.DetailsClass.__beerRecipientsItem_Created,
                    global::LightSwitchApplication.beerRecipientsItem.DetailsClass.__beerRecipientsItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.beerRecipientsItem __beerRecipientsItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.beerRecipientsItem> es)
            {
                return new global::LightSwitchApplication.beerRecipientsItem(es);
            }
            private static void __beerRecipientsItem_Created(global::LightSwitchApplication.beerRecipientsItem e)
            {
                e.beerRecipientsItem_Created();
            }
            private static bool __beerRecipientsItem_AllowSaveWithErrors(global::LightSwitchApplication.beerRecipientsItem e)
            {
                bool result = false;
                e.beerRecipientsItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string> name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem> countriesItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem> contactDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.contactDetails) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem> deliveries
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.deliveries) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; }
                new string name { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation countriesItem { get; set; }
                new global::System.Collections.IEnumerable contactDetails { get; }
                new global::System.Collections.IEnumerable deliveries { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.beerRecipientsItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string>.Entry
                    name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string>.Entry(
                        "name",
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_Stub,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_ComputeIsReadOnly,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_Validate,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_GetImplementationValue,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_SetImplementationValue,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._name_OnValueChanged);
                private static void _name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, object sf)
                {
                    c(d, ref d._name, sf);
                }
                private static bool _name_ComputeIsReadOnly(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    bool result = false;
                    e.name_IsReadOnly(ref result);
                    return result;
                }
                private static void _name_Validate(global::LightSwitchApplication.beerRecipientsItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.name_Validate(r);
                }
                private static string _name_GetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.ImplementationEntity.name;
                }
                private static void _name_SetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.name = v;
                }
                private static void _name_OnValueChanged(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    e.name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem>.Entry
                    countriesItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem>.Entry(
                        "countriesItem",
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_Stub,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_Validate,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_GetImplementationValue,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_SetImplementationValue,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_Refresh,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._countriesItem_OnValueChanged);
                private static void _countriesItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem>.Data> c, global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, object sf)
                {
                    c(d, ref d._countriesItem, sf);
                }
                private static bool _countriesItem_ComputeIsReadOnly(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    bool result = false;
                    e.countriesItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _countriesItem_Validate(global::LightSwitchApplication.beerRecipientsItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.countriesItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _countriesItem_GetCoreImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.ImplementationEntity.countriesItem;
                }
                private static global::LightSwitchApplication.countriesItem _countriesItem_GetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.countriesItem, global::LightSwitchApplication.countriesItem.DetailsClass>(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem, ref d._countriesItem);
                }
                private static void _countriesItem_SetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, global::LightSwitchApplication.countriesItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem, ref d._countriesItem, (i, ev) => i.countriesItem = ev, v);
                }
                private static void _countriesItem_Refresh(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.countriesItem, ref d._countriesItem);
                }
                private static void _countriesItem_OnValueChanged(global::LightSwitchApplication.beerRecipientsItem e)
                {
                    e.countriesItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem>.Entry
                    contactDetails = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem>.Entry(
                        "contactDetails",
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._contactDetails_Stub,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._contactDetails_GetReferencedEntities,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._contactDetails_GetEntityCollection);
                private static void _contactDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem>.Data> c, global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, object sf)
                {
                    c(d, ref d._contactDetails, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.contactDetailsItem> _contactDetails_GetReferencedEntities(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.contactDetailsItem, global::LightSwitchApplication.contactDetailsItem.DetailsClass>(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.contactDetails, ref d._contactDetails);
                }
                private static global::System.Collections.IEnumerable _contactDetails_GetEntityCollection(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.ImplementationEntity.contactDetails;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem>.Entry
                    deliveries = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem>.Entry(
                        "deliveries",
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._deliveries_Stub,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._deliveries_GetReferencedEntities,
                        global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties._deliveries_GetEntityCollection);
                private static void _deliveries_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem>.Data> c, global::LightSwitchApplication.beerRecipientsItem.DetailsClass d, object sf)
                {
                    c(d, ref d._deliveries, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.deliveriesItem> _deliveries_GetReferencedEntities(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>(global::LightSwitchApplication.beerRecipientsItem.DetailsClass.PropertySetProperties.deliveries, ref d._deliveries);
                }
                private static global::System.Collections.IEnumerable _deliveries_GetEntityCollection(global::LightSwitchApplication.beerRecipientsItem.DetailsClass d)
                {
                    return d.ImplementationEntity.deliveries;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, string>.Data _name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.countriesItem>.Data _countriesItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.contactDetailsItem>.Data _contactDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass, global::LightSwitchApplication.deliveriesItem>.Data _deliveries;
            
        }
    
        #endregion
    }
    
    #endregion
}
