

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Order : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität Order.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Order()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Order(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Order> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Order.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PK_orders
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.PK_orders);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_orders_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_orders_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_orders_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal price
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.price);
            }
            set
            {
                global::LightSwitchApplication.Order.DetailsClass.SetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.price, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void price_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void price_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool received
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.received);
            }
            set
            {
                global::LightSwitchApplication.Order.DetailsClass.SetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.received, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void received_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void received_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void received_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.orderedBeersItem> orderedBeers
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.orderedBeers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.orderedBeersItem> orderedBeersQuery
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetQuery(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.orderedBeers);
            }
        }

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.suppliersItem supplier
        {
            get
            {
                return global::LightSwitchApplication.Order.DetailsClass.GetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier);
            }
            set
            {
                global::LightSwitchApplication.Order.DetailsClass.SetValue(this, global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void supplier_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void supplier_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void supplier_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Order,
                global::LightSwitchApplication.Order.DetailsClass,
                global::LightSwitchApplication.Order.DetailsClass.IImplementation,
                global::LightSwitchApplication.Order.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.PK_orders;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>.Entry
                __OrderEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>.Entry(
                    global::LightSwitchApplication.Order.DetailsClass.__Order_CreateNew,
                    global::LightSwitchApplication.Order.DetailsClass.__Order_Created,
                    global::LightSwitchApplication.Order.DetailsClass.__Order_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Order __Order_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Order> es)
            {
                return new global::LightSwitchApplication.Order(es);
            }
            private static void __Order_Created(global::LightSwitchApplication.Order e)
            {
                e.Order_Created();
            }
            private static bool __Order_AllowSaveWithErrors(global::LightSwitchApplication.Order e)
            {
                bool result = false;
                e.Order_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Order.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int> PK_orders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.PK_orders) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal> price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.price) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool> received
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.received) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem> orderedBeers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.orderedBeers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem> supplier
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PK_orders { get; }
                new decimal price { get; set; }
                new bool received { get; set; }
                new global::System.Collections.IEnumerable orderedBeers { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation supplier { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int>.Entry
                    PK_orders = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int>.Entry(
                        "PK_orders",
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._PK_orders_Stub,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._PK_orders_ComputeIsReadOnly,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._PK_orders_Validate,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._PK_orders_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._PK_orders_OnValueChanged);
                private static void _PK_orders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Order.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int>.Data> c, global::LightSwitchApplication.Order.DetailsClass d, object sf)
                {
                    c(d, ref d._PK_orders, sf);
                }
                private static bool _PK_orders_ComputeIsReadOnly(global::LightSwitchApplication.Order e)
                {
                    bool result = false;
                    e.PK_orders_IsReadOnly(ref result);
                    return result;
                }
                private static void _PK_orders_Validate(global::LightSwitchApplication.Order e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PK_orders_Validate(r);
                }
                private static int _PK_orders_GetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.ImplementationEntity.PK_orders;
                }
                private static void _PK_orders_OnValueChanged(global::LightSwitchApplication.Order e)
                {
                    e.PK_orders_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal>.Entry
                    price = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal>.Entry(
                        "price",
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_Stub,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_ComputeIsReadOnly,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_Validate,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_GetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_SetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._price_OnValueChanged);
                private static void _price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Order.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Order.DetailsClass d, object sf)
                {
                    c(d, ref d._price, sf);
                }
                private static bool _price_ComputeIsReadOnly(global::LightSwitchApplication.Order e)
                {
                    bool result = false;
                    e.price_IsReadOnly(ref result);
                    return result;
                }
                private static void _price_Validate(global::LightSwitchApplication.Order e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.price_Validate(r);
                }
                private static decimal _price_GetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.ImplementationEntity.price;
                }
                private static void _price_SetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.price = v;
                }
                private static void _price_OnValueChanged(global::LightSwitchApplication.Order e)
                {
                    e.price_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool>.Entry
                    received = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool>.Entry(
                        "received",
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_Stub,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_ComputeIsReadOnly,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_Validate,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_GetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_SetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._received_OnValueChanged);
                private static void _received_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Order.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Order.DetailsClass d, object sf)
                {
                    c(d, ref d._received, sf);
                }
                private static bool _received_ComputeIsReadOnly(global::LightSwitchApplication.Order e)
                {
                    bool result = false;
                    e.received_IsReadOnly(ref result);
                    return result;
                }
                private static void _received_Validate(global::LightSwitchApplication.Order e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.received_Validate(r);
                }
                private static bool _received_GetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.ImplementationEntity.received;
                }
                private static void _received_SetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.received = v;
                }
                private static void _received_OnValueChanged(global::LightSwitchApplication.Order e)
                {
                    e.received_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem>.Entry
                    orderedBeers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem>.Entry(
                        "orderedBeers",
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._orderedBeers_Stub,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._orderedBeers_GetReferencedEntities,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._orderedBeers_GetEntityCollection);
                private static void _orderedBeers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Order.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem>.Data> c, global::LightSwitchApplication.Order.DetailsClass d, object sf)
                {
                    c(d, ref d._orderedBeers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.orderedBeersItem> _orderedBeers_GetReferencedEntities(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.orderedBeersItem, global::LightSwitchApplication.orderedBeersItem.DetailsClass>(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.orderedBeers, ref d._orderedBeers);
                }
                private static global::System.Collections.IEnumerable _orderedBeers_GetEntityCollection(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.ImplementationEntity.orderedBeers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem>.Entry
                    supplier = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem>.Entry(
                        "supplier",
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_Stub,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_ComputeIsReadOnly,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_Validate,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_GetCoreImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_GetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_SetImplementationValue,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_Refresh,
                        global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties._supplier_OnValueChanged);
                private static void _supplier_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Order.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem>.Data> c, global::LightSwitchApplication.Order.DetailsClass d, object sf)
                {
                    c(d, ref d._supplier, sf);
                }
                private static bool _supplier_ComputeIsReadOnly(global::LightSwitchApplication.Order e)
                {
                    bool result = false;
                    e.supplier_IsReadOnly(ref result);
                    return result;
                }
                private static void _supplier_Validate(global::LightSwitchApplication.Order e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.supplier_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _supplier_GetCoreImplementationValue(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.ImplementationEntity.supplier;
                }
                private static global::LightSwitchApplication.suppliersItem _supplier_GetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.suppliersItem, global::LightSwitchApplication.suppliersItem.DetailsClass>(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier, ref d._supplier);
                }
                private static void _supplier_SetImplementationValue(global::LightSwitchApplication.Order.DetailsClass d, global::LightSwitchApplication.suppliersItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier, ref d._supplier, (i, ev) => i.supplier = ev, v);
                }
                private static void _supplier_Refresh(global::LightSwitchApplication.Order.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Order.DetailsClass.PropertySetProperties.supplier, ref d._supplier);
                }
                private static void _supplier_OnValueChanged(global::LightSwitchApplication.Order e)
                {
                    e.supplier_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, int>.Data _PK_orders;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, decimal>.Data _price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, bool>.Data _received;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.orderedBeersItem>.Data _orderedBeers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Order, global::LightSwitchApplication.Order.DetailsClass, global::LightSwitchApplication.suppliersItem>.Data _supplier;
            
        }
    
        #endregion
    }
    
    #endregion
}
