

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class view_driver_nextDeliveriesItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität view_driver_nextDeliveriesItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public view_driver_nextDeliveriesItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public view_driver_nextDeliveriesItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.view_driver_nextDeliveriesItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void view_driver_nextDeliveriesItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void view_driver_nextDeliveriesItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> deliveryDate
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.deliveryDate);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.deliveryDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> invoiceNumber
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int carriage
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.carriage);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.carriage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void carriage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void carriage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void carriage_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int amount
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.amount);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.amount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string driver
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.driver);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.driver, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void driver_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void driver_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void driver_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int truckCapacity
        {
            get
            {
                return global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.truckCapacity);
            }
            set
            {
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.truckCapacity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void truckCapacity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void truckCapacity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void truckCapacity_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.view_driver_nextDeliveriesItem,
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass,
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.deliveryDate;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>.Entry
                __view_driver_nextDeliveriesItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.__view_driver_nextDeliveriesItem_CreateNew,
                    global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.__view_driver_nextDeliveriesItem_Created,
                    global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.__view_driver_nextDeliveriesItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.view_driver_nextDeliveriesItem __view_driver_nextDeliveriesItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.view_driver_nextDeliveriesItem> es)
            {
                return new global::LightSwitchApplication.view_driver_nextDeliveriesItem(es);
            }
            private static void __view_driver_nextDeliveriesItem_Created(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
            {
                e.view_driver_nextDeliveriesItem_Created();
            }
            private static bool __view_driver_nextDeliveriesItem_AllowSaveWithErrors(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
            {
                bool result = false;
                e.view_driver_nextDeliveriesItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>> deliveryDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.deliveryDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>> invoiceNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int> carriage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.carriage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int> amount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.amount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string> driver
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.driver) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int> truckCapacity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties.truckCapacity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Nullable<global::System.DateTime> deliveryDate { get; set; }
                new global::System.Nullable<int> invoiceNumber { get; set; }
                new int carriage { get; set; }
                new int amount { get; set; }
                new string driver { get; set; }
                new int truckCapacity { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    deliveryDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "deliveryDate",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_OnValueChanged);
                private static void _deliveryDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._deliveryDate, sf);
                }
                private static bool _deliveryDate_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.deliveryDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _deliveryDate_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.deliveryDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _deliveryDate_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.deliveryDate;
                }
                private static void _deliveryDate_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.deliveryDate = global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.TruncateDate(v);
                }
                private static void _deliveryDate_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.deliveryDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>>.Entry
                    invoiceNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "invoiceNumber",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_OnValueChanged);
                private static void _invoiceNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._invoiceNumber, sf);
                }
                private static bool _invoiceNumber_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.invoiceNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _invoiceNumber_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.invoiceNumber_Validate(r);
                }
                private static global::System.Nullable<int> _invoiceNumber_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.invoiceNumber;
                }
                private static void _invoiceNumber_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.invoiceNumber = v;
                }
                private static void _invoiceNumber_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.invoiceNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry
                    carriage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry(
                        "carriage",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._carriage_OnValueChanged);
                private static void _carriage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._carriage, sf);
                }
                private static bool _carriage_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.carriage_IsReadOnly(ref result);
                    return result;
                }
                private static void _carriage_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.carriage_Validate(r);
                }
                private static int _carriage_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.carriage;
                }
                private static void _carriage_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.carriage = v;
                }
                private static void _carriage_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.carriage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry
                    amount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry(
                        "amount",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._amount_OnValueChanged);
                private static void _amount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._amount, sf);
                }
                private static bool _amount_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.amount_IsReadOnly(ref result);
                    return result;
                }
                private static void _amount_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.amount_Validate(r);
                }
                private static int _amount_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.amount;
                }
                private static void _amount_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.amount = v;
                }
                private static void _amount_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.amount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string>.Entry
                    driver = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string>.Entry(
                        "driver",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._driver_OnValueChanged);
                private static void _driver_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._driver, sf);
                }
                private static bool _driver_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.driver_IsReadOnly(ref result);
                    return result;
                }
                private static void _driver_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.driver_Validate(r);
                }
                private static string _driver_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.driver;
                }
                private static void _driver_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.driver = v;
                }
                private static void _driver_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.driver_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry
                    truckCapacity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Entry(
                        "truckCapacity",
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_Stub,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_ComputeIsReadOnly,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_Validate,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_GetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_SetImplementationValue,
                        global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass.PropertySetProperties._truckCapacity_OnValueChanged);
                private static void _truckCapacity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._truckCapacity, sf);
                }
                private static bool _truckCapacity_ComputeIsReadOnly(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    bool result = false;
                    e.truckCapacity_IsReadOnly(ref result);
                    return result;
                }
                private static void _truckCapacity_Validate(global::LightSwitchApplication.view_driver_nextDeliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.truckCapacity_Validate(r);
                }
                private static int _truckCapacity_GetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.truckCapacity;
                }
                private static void _truckCapacity_SetImplementationValue(global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.truckCapacity = v;
                }
                private static void _truckCapacity_OnValueChanged(global::LightSwitchApplication.view_driver_nextDeliveriesItem e)
                {
                    e.truckCapacity_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _deliveryDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, global::System.Nullable<int>>.Data _invoiceNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data _carriage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data _amount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, string>.Data _driver;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.view_driver_nextDeliveriesItem, global::LightSwitchApplication.view_driver_nextDeliveriesItem.DetailsClass, int>.Data _truckCapacity;
            
        }
    
        #endregion
    }
    
    #endregion
}
