

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class DeliveryConfirmOperation : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität DeliveryConfirmOperation.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DeliveryConfirmOperation()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DeliveryConfirmOperation(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DeliveryConfirmOperation> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeliveryConfirmOperation_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeliveryConfirmOperation_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DeliveryId
        {
            get
            {
                return global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.DeliveryId);
            }
            set
            {
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.DeliveryId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeliveryId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeliveryId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeliveryId_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ExecutionError
        {
            get
            {
                return global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ExecutionError);
            }
            set
            {
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ExecutionError, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecutionError_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecutionError_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecutionError_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ErrorMessage
        {
            get
            {
                return global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ErrorMessage);
            }
            set
            {
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ErrorMessage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DeliveryConfirmOperation,
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass,
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.IImplementation,
                global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>.Entry
                __DeliveryConfirmOperationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>.Entry(
                    global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.__DeliveryConfirmOperation_CreateNew,
                    global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.__DeliveryConfirmOperation_Created,
                    global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.__DeliveryConfirmOperation_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DeliveryConfirmOperation __DeliveryConfirmOperation_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DeliveryConfirmOperation> es)
            {
                return new global::LightSwitchApplication.DeliveryConfirmOperation(es);
            }
            private static void __DeliveryConfirmOperation_Created(global::LightSwitchApplication.DeliveryConfirmOperation e)
            {
                e.DeliveryConfirmOperation_Created();
            }
            private static bool __DeliveryConfirmOperation_AllowSaveWithErrors(global::LightSwitchApplication.DeliveryConfirmOperation e)
            {
                bool result = false;
                e.DeliveryConfirmOperation_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int> DeliveryId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.DeliveryId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool> ExecutionError
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ExecutionError) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string> ErrorMessage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties.ErrorMessage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new int DeliveryId { get; set; }
                new bool ExecutionError { get; set; }
                new string ErrorMessage { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Data> c, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DeliveryConfirmOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.DeliveryConfirmOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Entry
                    DeliveryId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Entry(
                        "DeliveryId",
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_Stub,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_ComputeIsReadOnly,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_Validate,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_GetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_SetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._DeliveryId_OnValueChanged);
                private static void _DeliveryId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Data> c, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._DeliveryId, sf);
                }
                private static bool _DeliveryId_ComputeIsReadOnly(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    bool result = false;
                    e.DeliveryId_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeliveryId_Validate(global::LightSwitchApplication.DeliveryConfirmOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeliveryId_Validate(r);
                }
                private static int _DeliveryId_GetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.DeliveryId;
                }
                private static void _DeliveryId_SetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, int v)
                {
                    d.ImplementationEntity.DeliveryId = v;
                }
                private static void _DeliveryId_OnValueChanged(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    e.DeliveryId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool>.Entry
                    ExecutionError = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool>.Entry(
                        "ExecutionError",
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_Stub,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_ComputeIsReadOnly,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_Validate,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_GetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_SetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ExecutionError_OnValueChanged);
                private static void _ExecutionError_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool>.Data> c, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._ExecutionError, sf);
                }
                private static bool _ExecutionError_ComputeIsReadOnly(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    bool result = false;
                    e.ExecutionError_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExecutionError_Validate(global::LightSwitchApplication.DeliveryConfirmOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExecutionError_Validate(r);
                }
                private static bool _ExecutionError_GetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.ExecutionError;
                }
                private static void _ExecutionError_SetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.ExecutionError = v;
                }
                private static void _ExecutionError_OnValueChanged(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    e.ExecutionError_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string>.Entry
                    ErrorMessage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string>.Entry(
                        "ErrorMessage",
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_Stub,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_ComputeIsReadOnly,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_Validate,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_GetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_SetImplementationValue,
                        global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass.PropertySetProperties._ErrorMessage_OnValueChanged);
                private static void _ErrorMessage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._ErrorMessage, sf);
                }
                private static bool _ErrorMessage_ComputeIsReadOnly(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    bool result = false;
                    e.ErrorMessage_IsReadOnly(ref result);
                    return result;
                }
                private static void _ErrorMessage_Validate(global::LightSwitchApplication.DeliveryConfirmOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ErrorMessage_Validate(r);
                }
                private static string _ErrorMessage_GetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.ErrorMessage;
                }
                private static void _ErrorMessage_SetImplementationValue(global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ErrorMessage = v;
                }
                private static void _ErrorMessage_OnValueChanged(global::LightSwitchApplication.DeliveryConfirmOperation e)
                {
                    e.ErrorMessage_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, int>.Data _DeliveryId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, bool>.Data _ExecutionError;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DeliveryConfirmOperation, global::LightSwitchApplication.DeliveryConfirmOperation.DetailsClass, string>.Data _ErrorMessage;
            
        }
    
        #endregion
    }
    
    #endregion
}
