

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class deliveriesItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität deliveriesItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public deliveriesItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public deliveriesItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.deliveriesItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.deliveriesItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveriesItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveriesItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PK_deliveries
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.PK_deliveries);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_deliveries_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_deliveries_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PK_deliveries_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime orderDate
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.orderDate);
            }
            set
            {
                global::LightSwitchApplication.deliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.orderDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void orderDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void orderDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void orderDate_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime deliveryDate
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveryDate);
            }
            set
            {
                global::LightSwitchApplication.deliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveryDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> billingDate
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.billingDate);
            }
            set
            {
                global::LightSwitchApplication.deliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.billingDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void billingDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void billingDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void billingDate_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> invoiceNumber
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber);
            }
            set
            {
                global::LightSwitchApplication.deliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invoiceNumber_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.deliveredBeersItem> deliveredBeers
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveredBeers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.deliveredBeersItem> deliveredBeersQuery
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveredBeers);
            }
        }

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.beerRecipientsItem beerRecipient
        {
            get
            {
                return global::LightSwitchApplication.deliveriesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient);
            }
            set
            {
                global::LightSwitchApplication.deliveriesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerRecipient_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerRecipient_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void beerRecipient_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.deliveriesItem,
                global::LightSwitchApplication.deliveriesItem.DetailsClass,
                global::LightSwitchApplication.deliveriesItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.PK_deliveries;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>.Entry
                __deliveriesItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.deliveriesItem.DetailsClass.__deliveriesItem_CreateNew,
                    global::LightSwitchApplication.deliveriesItem.DetailsClass.__deliveriesItem_Created,
                    global::LightSwitchApplication.deliveriesItem.DetailsClass.__deliveriesItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.deliveriesItem __deliveriesItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.deliveriesItem> es)
            {
                return new global::LightSwitchApplication.deliveriesItem(es);
            }
            private static void __deliveriesItem_Created(global::LightSwitchApplication.deliveriesItem e)
            {
                e.deliveriesItem_Created();
            }
            private static bool __deliveriesItem_AllowSaveWithErrors(global::LightSwitchApplication.deliveriesItem e)
            {
                bool result = false;
                e.deliveriesItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int> PK_deliveries
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.PK_deliveries) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime> orderDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.orderDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime> deliveryDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveryDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>> billingDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.billingDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>> invoiceNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.invoiceNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem> deliveredBeers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveredBeers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem> beerRecipient
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PK_deliveries { get; }
                new global::System.DateTime orderDate { get; set; }
                new global::System.DateTime deliveryDate { get; set; }
                new global::System.Nullable<global::System.DateTime> billingDate { get; set; }
                new global::System.Nullable<int> invoiceNumber { get; set; }
                new global::System.Collections.IEnumerable deliveredBeers { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation beerRecipient { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int>.Entry
                    PK_deliveries = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int>.Entry(
                        "PK_deliveries",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._PK_deliveries_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._PK_deliveries_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._PK_deliveries_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._PK_deliveries_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._PK_deliveries_OnValueChanged);
                private static void _PK_deliveries_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PK_deliveries, sf);
                }
                private static bool _PK_deliveries_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.PK_deliveries_IsReadOnly(ref result);
                    return result;
                }
                private static void _PK_deliveries_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PK_deliveries_Validate(r);
                }
                private static int _PK_deliveries_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PK_deliveries;
                }
                private static void _PK_deliveries_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.PK_deliveries_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Entry
                    orderDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Entry(
                        "orderDate",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_GetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_SetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._orderDate_OnValueChanged);
                private static void _orderDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._orderDate, sf);
                }
                private static bool _orderDate_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.orderDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _orderDate_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.orderDate_Validate(r);
                }
                private static global::System.DateTime _orderDate_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.orderDate;
                }
                private static void _orderDate_SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.orderDate = global::LightSwitchApplication.deliveriesItem.DetailsClass.TruncateDate(v);
                }
                private static void _orderDate_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.orderDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Entry
                    deliveryDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Entry(
                        "deliveryDate",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_GetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_SetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveryDate_OnValueChanged);
                private static void _deliveryDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._deliveryDate, sf);
                }
                private static bool _deliveryDate_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.deliveryDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _deliveryDate_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.deliveryDate_Validate(r);
                }
                private static global::System.DateTime _deliveryDate_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.deliveryDate;
                }
                private static void _deliveryDate_SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.deliveryDate = global::LightSwitchApplication.deliveriesItem.DetailsClass.TruncateDate(v);
                }
                private static void _deliveryDate_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.deliveryDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    billingDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "billingDate",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_GetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_SetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._billingDate_OnValueChanged);
                private static void _billingDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._billingDate, sf);
                }
                private static bool _billingDate_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.billingDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _billingDate_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.billingDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _billingDate_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.billingDate;
                }
                private static void _billingDate_SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.billingDate = global::LightSwitchApplication.deliveriesItem.DetailsClass.TruncateDate(v);
                }
                private static void _billingDate_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.billingDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>>.Entry
                    invoiceNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "invoiceNumber",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_GetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_SetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._invoiceNumber_OnValueChanged);
                private static void _invoiceNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._invoiceNumber, sf);
                }
                private static bool _invoiceNumber_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.invoiceNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _invoiceNumber_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.invoiceNumber_Validate(r);
                }
                private static global::System.Nullable<int> _invoiceNumber_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.invoiceNumber;
                }
                private static void _invoiceNumber_SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.invoiceNumber = v;
                }
                private static void _invoiceNumber_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.invoiceNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem>.Entry
                    deliveredBeers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem>.Entry(
                        "deliveredBeers",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveredBeers_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveredBeers_GetReferencedEntities,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._deliveredBeers_GetEntityCollection);
                private static void _deliveredBeers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._deliveredBeers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.deliveredBeersItem> _deliveredBeers_GetReferencedEntities(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.deliveredBeersItem, global::LightSwitchApplication.deliveredBeersItem.DetailsClass>(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.deliveredBeers, ref d._deliveredBeers);
                }
                private static global::System.Collections.IEnumerable _deliveredBeers_GetEntityCollection(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.deliveredBeers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem>.Entry
                    beerRecipient = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem>.Entry(
                        "beerRecipient",
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_Stub,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_ComputeIsReadOnly,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_Validate,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_GetCoreImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_GetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_SetImplementationValue,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_Refresh,
                        global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties._beerRecipient_OnValueChanged);
                private static void _beerRecipient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.deliveriesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem>.Data> c, global::LightSwitchApplication.deliveriesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._beerRecipient, sf);
                }
                private static bool _beerRecipient_ComputeIsReadOnly(global::LightSwitchApplication.deliveriesItem e)
                {
                    bool result = false;
                    e.beerRecipient_IsReadOnly(ref result);
                    return result;
                }
                private static void _beerRecipient_Validate(global::LightSwitchApplication.deliveriesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.beerRecipient_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _beerRecipient_GetCoreImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.beerRecipient;
                }
                private static global::LightSwitchApplication.beerRecipientsItem _beerRecipient_GetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.beerRecipientsItem, global::LightSwitchApplication.beerRecipientsItem.DetailsClass>(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient, ref d._beerRecipient);
                }
                private static void _beerRecipient_SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass d, global::LightSwitchApplication.beerRecipientsItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient, ref d._beerRecipient, (i, ev) => i.beerRecipient = ev, v);
                }
                private static void _beerRecipient_Refresh(global::LightSwitchApplication.deliveriesItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.deliveriesItem.DetailsClass.PropertySetProperties.beerRecipient, ref d._beerRecipient);
                }
                private static void _beerRecipient_OnValueChanged(global::LightSwitchApplication.deliveriesItem e)
                {
                    e.beerRecipient_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, int>.Data _PK_deliveries;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Data _orderDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.DateTime>.Data _deliveryDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _billingDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::System.Nullable<int>>.Data _invoiceNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.deliveredBeersItem>.Data _deliveredBeers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.deliveriesItem, global::LightSwitchApplication.deliveriesItem.DetailsClass, global::LightSwitchApplication.beerRecipientsItem>.Data _beerRecipient;
            
        }
    
        #endregion
    }
    
    #endregion
}
